version: '3'
services:
  m2tb:
    container_name: m2tb
    build: .
    image: mail2telegram/bot:dev
    restart: always
#    entrypoint: ['php', 'index.php']
    volumes:
      - .:/app
      - ./docker/app/conf/php/dev.ini:/usr/local/etc/php/conf.d/dev.ini
      - ./docker/app/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      - PHAN_DISABLE_XDEBUG_WARN=1
      - PHAN_ALLOW_XDEBUG=0
      - PHP_IDE_CONFIG=serverName=app
